services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: booking-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-booking} -d ${POSTGRES_DB:-booking_db}']
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Backend API
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: booking-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      postgres:
        condition: service_healthy

  # Nuxt 4 Frontend
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: booking-frontend
    restart: unless-stopped
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:3000/api
      - NUXT_API_BASE_INTERNAL=http://backend:3000/api
    ports:
      - '3001:3000'
    depends_on:
      - backend

  # Swagger UI for API Documentation
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: booking-swagger-ui
    restart: unless-stopped
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
      BASE_URL: /
      DISPLAY_REQUEST_DURATION: 'true'
      DEEP_LINKING: 'true'
      TRY_IT_OUT_ENABLED: 'true'
    ports:
      - '8080:8080'
    volumes:
      - ./openapi.yaml:/openapi/openapi.yaml:ro

  # Prisma Studio for Database Management
  prisma-studio:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      target: builder
    container_name: booking-prisma-studio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5555:5555'
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app/packages/backend
    command: pnpm prisma studio --port 5555 --browser none

volumes:
  postgres-data:
    driver: local
