packages:
  - packages/*

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - vue-demi
