name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter backend exec prisma generate

      - name: Run linter (backend)
        run: pnpm --filter backend lint

      - name: Run linter (frontend)
        run: pnpm --filter frontend lint

      - name: Run unit tests (backend)
        run: pnpm --filter backend test

      - name: Run unit tests (frontend)
        run: pnpm --filter frontend test

      - name: Build backend
        run: pnpm --filter backend build

      - name: Build frontend
        run: pnpm --filter frontend build
        env:
          NUXT_PUBLIC_API_BASE: http://localhost:3000/api
